services:
  mongodb:
    image: mongo:8.0.10
    container_name: inventory-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
